id: ID024926C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T18:50:21+00:00'
last_modified: '2022-06-07T12:24:18.760967+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG873
  title: བོད་ལྗོངས་ཆོས་ལུགས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    4B4B:
      image_group_id: I1KG930
      title: ''
      total_pages: 234
      order: 1
      base_file: 4B4B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
